import * as mongodb from "mongodb";

export interface Employee {
    name:string;
    position: string;
    level: "junior" | "mid" | "senior";
    _id?:mongodb.ObjectId; //optionally our employees will have an _id field which is a mongodb object id 
    //optional bc generated by mongodb 
    //when we retreive date we will see this field
    //optionality is sybolized by ?
}